#! /bin/bash
TYPE=$1
APP_DIR="/Users/akio.fujiwara/zelda-allstars/zelda-cms"
case $TYPE in
	"conf" | "config")
		echo $APP_DIR/config/;;
	"dc" | "decorators")
		echo $APP_DIR/app/decorators/;;
	"sr" | "services")
		echo $APP_DIR/app/services/;;
	"cont" | "controllers")
		echo $APP_DIR/app/controllers;;
	"model" | "models")
		echo $APP_DIR/app/models;;
	"view" | "views")
		echo $APP_DIR/app/views;;
	"ap" | "api")
		echo $APP_DIR/app/api;;
	"ng" | "ng-app")
		echo $APP_DIR/app/ng-app;;
	"js" | "javascript")
		echo $APP_DIR/app/assets/javascripts;;
	"css" | "stylesheet")
		echo $APP_DIR/app/assets/stylesheets;;
	"hp" | "help")
		echo $APP_DIR/app/helpers;;
	*)
		echo $APP_DIR/;;
esac
